[tool.black]
line-length = 100
skip-string-normalization = true
extend-exclude = '''
/(
  # exclude migrations
  | migrations
)/
'''

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if typing.TYPE_CHECKING:",
  "if TYPE_CHECKING:",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
skip = [".ipython"]
remove_redundant_aliases = true
